//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatu
    {
        public DocumentStatu()
        {
            this.InfoGatherings = new HashSet<InfoGathering>();
            this.SDDocumentations = new HashSet<SDDocumentation>();
        }
    
        public int Id { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<InfoGathering> InfoGatherings { get; set; }
        public virtual ICollection<SDDocumentation> SDDocumentations { get; set; }
    }
}
