//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLink
    {
        public DocumentLink()
        {
            this.InfoGatherings = new HashSet<InfoGathering>();
            this.InfoGatherings1 = new HashSet<InfoGathering>();
            this.SDDocumentations = new HashSet<SDDocumentation>();
            this.SDDocumentations1 = new HashSet<SDDocumentation>();
        }
    
        public int Id { get; set; }
        public string link { get; set; }
        public int Access_id { get; set; }
    
        public virtual DocumentAccess DocumentAccess { get; set; }
        public virtual ICollection<InfoGathering> InfoGatherings { get; set; }
        public virtual ICollection<InfoGathering> InfoGatherings1 { get; set; }
        public virtual ICollection<SDDocumentation> SDDocumentations { get; set; }
        public virtual ICollection<SDDocumentation> SDDocumentations1 { get; set; }
    }
}
