//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoGathering
    {
        public InfoGathering()
        {
            this.InfoGathering1 = new HashSet<InfoGathering>();
            this.InfoGathLogs = new HashSet<InfoGathLog>();
        }
    
        public int id { get; set; }
        public string searchableAlias { get; set; }
        public Nullable<int> infoGathLink_id { get; set; }
        public string infoGathTitle { get; set; }
        public string assignmentGroup { get; set; }
        public string supportInfo { get; set; }
        public string supportHours { get; set; }
        public string contactInfo { get; set; }
        public string passwordAttributes { get; set; }
        public string passwordTitle { get; set; }
        public Nullable<int> PasswordHyperlink_id { get; set; }
        public string aliases { get; set; }
        public int Status_id { get; set; }
        public Nullable<int> Original_id { get; set; }
    
        public virtual DocumentLink DocumentLink { get; set; }
        public virtual DocumentLink DocumentLink1 { get; set; }
        public virtual DocumentStatu DocumentStatu { get; set; }
        public virtual ICollection<InfoGathering> InfoGathering1 { get; set; }
        public virtual InfoGathering InfoGathering2 { get; set; }
        public virtual ICollection<InfoGathLog> InfoGathLogs { get; set; }
    }
}
