//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkLogin
    {
        public NetworkLogin()
        {
            this.InfoGathLogs = new HashSet<InfoGathLog>();
            this.ProbTrackLogs = new HashSet<ProbTrackLog>();
            this.SDDocLogs = new HashSet<SDDocLog>();
            this.UsageLogs = new HashSet<UsageLog>();
        }
    
        public int id { get; set; }
        public string ntID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<InfoGathLog> InfoGathLogs { get; set; }
        public virtual ICollection<ProbTrackLog> ProbTrackLogs { get; set; }
        public virtual ICollection<SDDocLog> SDDocLogs { get; set; }
        public virtual ICollection<UsageLog> UsageLogs { get; set; }
    }
}
