//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int id { get; set; }
        public string ipAddress { get; set; }
        public string serialNumber { get; set; }
        public string manufacturer { get; set; }
        public string modelNumber { get; set; }
        public string location { get; set; }
        public string supportGroup { get; set; }
        public string lastHardwareScan { get; set; }
        public string ciDescription { get; set; }
    }
}
