//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDDocLog
    {
        public int id { get; set; }
        public System.DateTime dateTime { get; set; }
        public int NTID_id { get; set; }
        public int SDDocumentation_id { get; set; }
    
        public virtual NetworkLogin NetworkLogin { get; set; }
        public virtual SDDocumentation SDDocumentation { get; set; }
    }
}
